export enum LevelTypes {
    INCREASED = 'INCREASED',
    NORMAL = 'NORMAL',
    DECREASED = 'DECREASED',
    DEGREE_0 = "DEGREE_0",
    DEGREE_I = "DEGREE_I",
    DEGREE_II = "DEGREE_II",
    DEGREE_III = "DEGREE_III",
    DEGREE_IV = "DEGREE_IV",
    BELOW_NORMAL = "BELOW_NORMAL",
    ABOVE_NORMAL = "ABOVE_NORMAL"
}