export enum LevelTypes {
    INCREASED = 'INCREASED',
    NORMAL = 'NORMAL',
    DECREASED = 'DECREASED',
    DEGREE_0 = "DEGREE_0",
    DEGREE_I = "DEGREE_I",
    DEGREE_II = "DEGREE_II",
    DEGREE_III = "DEGREE_III",
    DEGREE_IV = "DEGREE_IV",
    BELOW_NORMAL_1 = "BELOW_NORMAL_1",
    ABOVE_NORMAL_1 = "ABOVE_NORMAL_1",
    BELOW_NORMAL_2 = "BELOW_NORMAL_2",
    ABOVE_NORMAL_2 = "ABOVE_NORMAL_2"
}